jenkins:
  systemMessage: "Jenkins"
  securityRealm:
    github:
      githubWebUri: "https://github.com"
      githubApiUri: "https://api.github.com"
      clientID: "${GH_CLIENT_ID}" # Environment variable
      clientSecret: "${GH_CLIENT_SECRET}" # Environment variable
      oauthScopes: "read:org,user:email"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  
  clouds:
  - amazonEC2:
      cloudName: "AWS"
      credentialsId: "aws" # TODO: give jenkins own credentials
      privateKey: |-
        "${AWS_AGENT_KEY}"
      region: "ap-southeast-2"
      templates:
      - ami: "ami-0153a4eb8b94cfb5e" # TODO: work out how this should be
        amiType:
          unixData:
            sshPort: "22"
        associatePublicIp: false
        connectBySSHProcess: false
        connectionStrategy: PUBLIC_IP # TODO jumpboxes and stuff
        deleteRootOnTermination: false
        description: "centos"
        ebsOptimized: false
        idleTerminationMinutes: "15"
        labelString: "centos"
        maxTotalUses: -1
        minimumNumberOfInstances: 0
        minimumNumberOfSpareInstances: 0
        mode: NORMAL
        monitoring: false
        numExecutors: 1
        remoteAdmin: "ec2-user"
        remoteFS: "/home/ec2-user"
        stopOnTerminate: false
        t2Unlimited: false
        type: T2Micro
        useDedicatedTenancy: false
        useEphemeralDevices: false
      useInstanceProfileForCredentials: false

credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          scope: GLOBAL
          id: "GH_PAT"
          username: "ProgrammerNick"
          password: "${GH_PAT}" # Environment variable
          description: "GitHub Personal Access Token for ProgrammerNick"
      - string:
          scope: GLOBAL
          id: "GH_CLIENT_ID"
          secret: "${GH_CLIENT_ID}" # Environment variable
          description: "GitHub Client ID"
      - string:
          scope: GLOBAL
          id: "GH_CLIENT_SECRET"
          secret: "${GH_CLIENT_SECRET}" # Environment variable
          description: "GitHub Client Secret"
      - aws:
          accessKey: "${AWS_ACCESS_KEY}"
          description: "jenkins-aws"
          id: "aws"
          scope: GLOBAL
          secretKey: "${AWS_SECRET_KEY}"

unclassified:
  simple-theme-plugin:
    elements:
    - cssUrl:
        url: "https://cdn.rawgit.com/afonsof/jenkins-material-theme/gh-pages/dist/material-indigo.css"
# jobs:
#   - script: >
#       job('DSL_Seed') {
#           triggers {
#               hudsonStartupTrigger {
#                   quietPeriod("10")
#                   runOnChoice("ON_CONNECT")
#                   label("master")
#                   nodeParameterName("")
#               }
#           }
#           environmentVariables {
#             env('CLASSPATH', '$CLASSPATH:jobs/Docker')
#           }
#           scm {
#               git {
#                   remote {
#                       github('ProgrammerNick/jenkins', 'https')
#                       credentials('GH_PAT')
#                   }
#                   branch("master")
#               }
#           }
#           steps {
#               dsl {
#                 external("**/*JobDsl.groovy")
#               }
#           }
#       }